import { useState } from 'react';
import { getWeb3State } from '../utils/web3';
import { ethers } from 'ethers';
import { Cpu, CheckCircle2, Loader2, Leaf } from 'lucide-react';

export default function MintingHub() {
  const [isMinting, setIsMinting] = useState(false);
  const [txHash, setTxHash] = useState(null);
  const [sensorData, setSensorData] = useState("SolarFarm_APU_KualaLumpur_1Tonne");
  const [mintedTokenId, setMintedTokenId] = useState(null); // NEW: Explicitly tracks the minted ID

  const executeOracleMint = async () => {
    try {
      setIsMinting(true);
      setTxHash(null);
      setMintedTokenId(null);

      const { signer, contract } = await getWeb3State();
      const userAddress = await signer.getAddress();
      
      // THE 100 GWEI SLEDGEHAMMER
      // Mathematically guarantees the transaction will not be dropped by Amoy congestion
      const txOverrides = {
        maxPriorityFeePerGas: ethers.parseUnits("100", "gwei"),
        maxFeePerGas: ethers.parseUnits("100", "gwei")
      };

      const transaction = await contract.mintCredit(userAddress, sensorData, txOverrides);
      const receipt = await transaction.wait();
      setTxHash(receipt.hash);

      // --- BULLETPROOF TOKEN ID EXTRACTION ---
      let decodedTokenId = 'Unknown';
      
      for (const log of receipt.logs) {
        try {
          const parsedLog = contract.interface.parseLog(log);
          // A Mint is ALWAYS a Transfer from the ZeroAddress
          if (parsedLog && parsedLog.name === 'Transfer' && parsedLog.args[0] === ethers.ZeroAddress) {
            decodedTokenId = parsedLog.args[2].toString();
            break;
          }
        } catch (e) {
          // Ignore unrelated system logs
        }
      }
      
      setMintedTokenId(decodedTokenId); // Lock it into the UI

      // --- CLIENT-SIDE INDEXER CACHE ---
      const newAuditRecord = {
        id: Date.now(),
        type: 'MINT',
        token: decodedTokenId,
        hash: receipt.hash,
        timestamp: new Date().toLocaleString(),
        entity: `${userAddress.substring(0, 6)}...${userAddress.substring(38)}`,
        status: 'Confirmed'
      };

      const existingCache = JSON.parse(localStorage.getItem('carbonTrustIndexer') || '[]');
      localStorage.setItem('carbonTrustIndexer', JSON.stringify([newAuditRecord, ...existingCache]));

    } catch (error) {
      console.error(error);
      alert("Cryptographic Execution Failed: " + (error.reason || error.message));
    } finally {
      setIsMinting(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6">
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Oracle Simulation & Minting Hub</h2>
        <p className="text-gray-500">Bypassing legacy audits via direct IoT-to-Blockchain state anchoring.</p>
      </div>

      <div className="bg-white p-8 rounded-xl border border-gray-200 shadow-sm">
        <div className="flex items-start space-x-6">
          <div className="p-4 bg-green-100 text-green-700 rounded-2xl">
            <Cpu size={32} />
          </div>
          
          <div className="flex-1 space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-gray-900">Simulated IoT Telemetry Feed</h3>
              <p className="text-sm text-gray-500">In production, this payload is dynamically generated by physical sensors reaching the 1-tonne CO2e threshold.</p>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-700">Metadata Payload (Immutable string)</label>
              <input 
                type="text" 
                value={sensorData}
                onChange={(e) => setSensorData(e.target.value)}
                disabled={isMinting}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 outline-none transition-all disabled:bg-gray-100"
              />
            </div>

            <button
              onClick={executeOracleMint}
              disabled={isMinting}
              className={`w-full flex justify-center items-center space-x-2 py-3 px-4 rounded-lg font-bold text-white transition-all duration-200 ${
                isMinting ? 'bg-green-400 cursor-not-allowed' : 'bg-green-600 hover:bg-green-700 shadow-md'
              }`}
            >
              {isMinting ? (
                <>
                  <Loader2 className="animate-spin" size={20} />
                  <span>Awaiting Polygon Consensus...</span>
                </>
              ) : (
                <>
                  <Leaf size={20} />
                  <span>Execute Smart Contract Mint</span>
                </>
              )}
            </button>

            {/* UPGRADED SUCCESS BANNER WITH EXPLICIT TOKEN ID */}
            {txHash && (
              <div className="mt-4 p-5 bg-emerald-50 border border-emerald-200 rounded-xl flex items-start space-x-3">
                <CheckCircle2 className="text-emerald-600 mt-0.5" size={24} />
                <div>
                  <h4 className="text-base font-bold text-emerald-900">Asset Cryptographically Secured</h4>
                  <p className="text-sm text-emerald-800 mt-1 font-bold">
                    Assigned Token ID: <span className="bg-emerald-200 px-2 py-0.5 rounded text-emerald-900">#{mintedTokenId}</span>
                  </p>
                  <p className="text-xs text-emerald-600 mt-2 break-all font-mono">
                    Tx Hash: {txHash}
                  </p>
                  <a 
                    href={`https://amoy.polygonscan.com/tx/${txHash}`} 
                    target="_blank" 
                    rel="noreferrer"
                    className="text-xs font-bold text-emerald-700 hover:text-emerald-900 underline mt-2 inline-block"
                  >
                    Verify on PolygonScan Explorer →
                  </a>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}